# Generated by Django 3.2 on 2021-04-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='create_date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.IntegerField(),
        ),
    ]
