# Generated by Django 3.2 on 2021-05-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_course_course_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='count',
            field=models.CharField(blank=True, choices=[('12', '12'), ('24', '24'), ('36', '36'), ('48', '48')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='library',
            field=models.CharField(blank=True, choices=[('R(1:20)', 'R(1:20)'), ('S(1:40)', 'S(1:40)'), ('I(2:00)', 'I(2:00)')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='main',
            field=models.CharField(blank=True, choices=[('Library', 'Library'), ('Voca', 'Voca'), ('NF', 'Library')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='voca_library',
            field=models.CharField(blank=True, choices=[('RV(1:40)', 'RV(1:40)'), ('SV(2:00)', 'SV(2:00)'), ('IV(2:20)', 'I(2:20)')], max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
