# Generated by Django 3.2 on 2021-05-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210504_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='modify_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
